# general settings
name: SR_x6_5
model_type: EDVRModel
scale: 6
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: REDS4
    type: REDSDataset
    #dataroot_gt: datasets/edvr_ds_1080/train/gt/
    dataroot_gt: datasets/edvr_ds/train_fin/gt_4k
    #dataroot_lq: datasets/edvr_ds_1080/train/lq_540/
    dataroot_lq: datasets/edvr_ds/train_fin/lq_360
    #meta_info_file: datasets/edvr_ds_1080/train/ds_meta.txt
    meta_info_file: datasets/edvr_ds/train_fin/gt_4k/ds_meta.txt
    dataroot_flow: ~
    val_partition: official
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    io_backend:
      type: disk
    num_frame: 5
    gt_size: 240
    use_flip: true
    use_rot: true
    cache_data: false
    padding: reflection_circle
    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name:  REDS4
    type: VideoTestDataset
    #dataroot_gt: datasets/edvr_ds/val_fin/gt/
    #dataroot_lq: datasets/edvr_ds/val_fin/lq/
    dataroot_gt: datasets/val_video/gt/
    dataroot_lq: datasets/val_video/lq_360/
    num_frame: 5
    io_backend:
      type: disk
    cache_data: false
    padding: reflection_circle

# network structures
network_g:
  
  type: EDVR
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 128
  num_frame: 5
  deformable_groups: 8
  num_extract_block: 5
  num_reconstruct_block: 40
  center_frame_idx: ~
  hr_in: false
  with_predeblur: false
  with_tsa: true
  upscale: 6
  scale_1: 2
  scale_2: 3

# path
path:
  #pretrain_network_g: pretrain_model/EDVR_L_x4_SR_Vimeo90K_official-162b54e4.pth
  #pretrain_network_g: pretrain_model/EDVR_L_x4_SR_REDS_official-9f5f5039.pth
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 4e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [50000]
    gamma: 0.5
    #type: CosineAnnealingRestartLR
    #periods: [50000, 100000, 150000, 150000, 150000]
    #restart_weights: [1, 0.5, 0.5, 0.5, 0.5]
    #eta_min: !!float 1e-7



  total_iter: 8000
  warmup_iter: -1  # no warm up
  tsa_iter: 8000
  dcn_lr_mul: 1
  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: sum


# validation settings
val:
  val_freq: !!float 8e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border:  1
      test_y_channel: false
    ssim:   
      type: calculate_ssim
      crop_border: 1
      test_y_channel: false
    niqe:
      type: calculate_niqe
      crop_border: 1

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500